### ISSUE TITLE
Failed to start application on hoot.glitch.me

### ISSUE THREAD

**Issue by bennycode** [readmeio/hoot#218]
Hi, I wanted to checkout your project and visited [hoot.glitch.me](https://hoot.glitch.me/) but unfortunately this page responds with an error:

> failed to start application on hoot.glitch.me
>
> This is most likely because your project has a code error.
> Check your project logs, fix the error and try again.

**Comment by kanadgupta** [comment]
Weird, looks like the application didn't like the Node 14 requirement in the `package.json`. I bumped it down to 12 and it appears to be up again. We also don't really recommend the Glitch link anymore, so I updated it to [hoot.at](https://hoot.at)!
